# Runs all playbooks for setting up services built on top of the IDR

### Ingress services
- import_playbook: idr-ftp.yml

### Export services
- import_playbook: idr-export.yml

## Search services
- import_playbook: idr-elasticsearch.yml
- import_playbook: idr-searchengine.yml
- import_playbook: idr-searchengine_nginx.yml
## Restore searchengine data if existence
- import_playbook: restore_searchengine_data.yml
